title: Project Mobility and Fuel Demand Under COVID-19
description: We take the pandemic data from COVID-19 epidemiology model to predict the impact of COVID-19 on transportation mobility and fuel demand in the US
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman