title: Machine Learning Model to Project the Impact of COVID-19 on U.S. Motor Gasoline Demand
description: We connect the COVID-19 statistics with personal mobility changes and project future mobility and fuel demand using COVID-19 epidemiology model
show_downloads: true
google_analytics: UA-158804899-2
theme: jekyll-theme-cayman
