title: COVID-19 Mobility and Fuel Demand Projection Using Machine Learning
description: We take the pandemic data from COVID-19 epidemiology model to predict the impact of COVID-19 on \ transportation mobility and fuel demand in the US
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman